### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [soumikshah/Plutus-InvestmentTracker#46]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 28  warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on Plutus-InvestmentTracker (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure). 

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve Plutus-InvestmentTracker's security, and the quality of the reports of static analysis tools.
(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by soumikshah** [comment]
Hello, I would like to fix all the vulnerabilities that you found. Please contact me at [me@soumikshah.com](mailto:me@soumikshah.com)

**Comment by misterAnderson90** [comment]
Hello Soumik,

I sent the gists to your e-mail. 

Please let me know if you need to clarify anything.
